version: '3'

services:
  teledrive:
    command: bash -c "export NODE_OPTIONS='--openssl-legacy-provider --no-experimental-fetch' && yarn api prisma migrate deploy || yarn api prisma migrate resolve --applied "20220420012853_init" && node api/dist/index.js"
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        REACT_APP_TG_API_ID: ${TG_API_ID}
        REACT_APP_TG_API_HASH: ${TG_API_HASH}
    environment:
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@db:5432/teledrive?connect_timeout=60&pool_timeout=60&socket_timeout=60
      REDIS_URI: redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: teledrive
    volumes:
      - teledrive_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always

volumes:
  teledrive_data:
  teledrive_postgres_data:
